language: node_js
node_js:
- '0.10'
script:
- grunt ci-build
deploy:
  provider: npm
  email: andre.torgal@gmail.com
  api_key:
    secure: j2FbNt2Wl5JRikmAuhYXkYKBCV3Dq4Ya0Jm70Q4l5+XUYKuCrkdTYfGkZpjodwCtCdXA6bdHNtp0w+sZVitCVe2pSZvO5ETm466LILirqLEOz48TBG+TY0s7k3LCFarinZTC2fv6Bcu2GX/9L4tk3ysTem9wRGFd2rubtLwBMdk=
  on:
    tags: true
    all_branches: true
    repo: andrezero/grunt-ngindex
